# Generated by Django 3.2.3 on 2022-05-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VOD', models.CharField(max_length=1000, unique=True)),
                ('streamerName', models.CharField(max_length=1000)),
                ('positiveComments', models.BigIntegerField(blank=True, null=True)),
                ('negativeComments', models.BigIntegerField(blank=True, null=True)),
                ('mostCommonWord', models.CharField(max_length=1000)),
                ('mostPositiveUser', models.CharField(max_length=1000)),
                ('mostNegativeUser', models.CharField(max_length=1000)),
            ],
        ),
    ]
